import { Meta, StoryObj } from '@storybook/react';
import { Tabs } from './Tabs';
declare const meta: Meta<typeof Tabs>;
export default meta;
type Story = StoryObj<typeof Tabs>;
export declare const Default: Story;
export declare const Border: Story;
export declare const Lift: Story;
export declare const Box: Story;
export declare const Controlled: Story;
export declare const Disabled: Story;
export declare const Sizes: Story;
