import { Meta, StoryObj } from '@storybook/react';
import { Alert } from './Alert';
declare const meta: Meta<typeof Alert>;
export default meta;
type Story = StoryObj<typeof Alert>;
export declare const Default: Story;
export declare const WithColors: Story;
export declare const WithDescription: Story;
export declare const WithActionButtons: Story;
export declare const Soft: Story;
export declare const Outline: Story;
export declare const Dash: Story;
