export const DEFAULT_THEME = 'dark';
export const STORAGE_KEY = 'sb-stratosphere-ui-theme';

export const THEMES = {
  light: 'light',
  dark: 'dark',
  cupcake: 'cupcake',
  bumblebee: 'bumblebee',
  emerald: 'emerald',
  corporate: 'corporate',
  synthwave: 'synthwave',
  retro: 'retro',
  cyberpunk: 'cyberpunk',
  valentine: 'valentine',
  halloween: 'halloween',
  garden: 'garden',
  forest: 'forest',
  aqua: 'aqua',
  lofi: 'lofi',
  pastel: 'pastel',
  fantasy: 'fantasy',
  wireframe: 'wireframe',
  black: 'black',
  luxury: 'luxury',
  dracula: 'dracula',
  cmyk: 'cmyk',
  autumn: 'autumn',
  business: 'business',
  acid: 'acid',
  lemonade: 'lemonade',
  night: 'night',
  coffee: 'coffee',
  winter: 'winter',
  dim: 'dim',
  nord: 'nord',
  sunset: 'sunset',
};
