export declare const DEFAULT_THEME = "dark";
export declare const STORAGE_KEY = "sb-stratosphere-ui-theme";
export declare const THEMES: {
    light: string;
    dark: string;
    cupcake: string;
    bumblebee: string;
    emerald: string;
    corporate: string;
    synthwave: string;
    retro: string;
    cyberpunk: string;
    valentine: string;
    halloween: string;
    garden: string;
    forest: string;
    aqua: string;
    lofi: string;
    pastel: string;
    fantasy: string;
    wireframe: string;
    black: string;
    luxury: string;
    dracula: string;
    cmyk: string;
    autumn: string;
    business: string;
    acid: string;
    lemonade: string;
    night: string;
    coffee: string;
    winter: string;
    dim: string;
    nord: string;
    sunset: string;
};
