import { Meta, StoryObj } from '@storybook/react';
import { Avatar } from './Avatar';
declare const meta: Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof Avatar>;
export declare const Default: Story;
export declare const Rounded: Story;
export declare const Sizes: Story;
export declare const WithRing: Story;
export declare const WithOnlineStatus: Story;
export declare const WithOfflineStatus: Story;
export declare const WithPlaceholderText: Story;
export declare const WithAvatarGroup: Story;
